// rn-fluid-calendar — Default Themes

/** @type {import('./index.d').CalendarTheme} */
export const LIGHT_THEME = {
  backgroundColor: '#FFFFFF',
  dayTextColor: '#1A1A2E',
  disabledDayTextColor: '#C8C8D4',
  todayTextColor: '#FFFFFF',
  todayBackgroundColor: '#6C63FF',
  headerTextColor: '#1A1A2E',
  headerBackgroundColor: '#FFFFFF',
  weekdayTextColor: '#9090A4',
  markedDateBackgroundColor: '#6C63FF',
  markedDateTextColor: '#FFFFFF',
  dotColor: '#6C63FF',
  arrowColor: '#6C63FF',
  borderRadius: 20,
  fontFamily: undefined,
  dayFontSize: 14,
  weekdayFontSize: 12,
  headerFontSize: 16,
  dayFontWeight: '400',
  headerFontWeight: '700',
  dayGap: 4,
  rowGap: 6,
  dayCellPadding: 4,
  containerPadding: 16,
  elevation: 8,
  shadowColor: '#000000',
  dayCellSize: 36,
  borderWidth: 0,
  borderColor: '#E0E0E0',
  rangeStartEndBackgroundColor: '#6C63FF',
  rangeFillColor: '#EAE8FF',
};

/** @type {import('./index.d').CalendarTheme} */
export const DARK_THEME = {
  backgroundColor: '#12121E',
  dayTextColor: '#E8E8F4',
  disabledDayTextColor: '#3A3A52',
  todayTextColor: '#FFFFFF',
  todayBackgroundColor: '#7B72FF',
  headerTextColor: '#E8E8F4',
  headerBackgroundColor: '#12121E',
  weekdayTextColor: '#5A5A7A',
  markedDateBackgroundColor: '#7B72FF',
  markedDateTextColor: '#FFFFFF',
  dotColor: '#7B72FF',
  arrowColor: '#7B72FF',
  borderRadius: 20,
  fontFamily: undefined,
  dayFontSize: 14,
  weekdayFontSize: 12,
  headerFontSize: 16,
  dayFontWeight: '400',
  headerFontWeight: '700',
  dayGap: 4,
  rowGap: 6,
  dayCellPadding: 4,
  containerPadding: 16,
  elevation: 12,
  shadowColor: '#000000',
  dayCellSize: 36,
  borderWidth: 1,
  borderColor: '#2A2A3E',
  rangeStartEndBackgroundColor: '#7B72FF',
  rangeFillColor: '#1E1E38',
};
